---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: TODO_CF_EMAIL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        cnameStrategy: None
        cloudflare:
          email: TODO_LE_EMAIL
          apiTokenSecretRef:
            name: cert-manager-secret
            key: CF_API_TOKEN
      selector:
        dnsZones:
        - TODO_ZONE
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: TODO_CF_EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cnameStrategy: None
        cloudflare:
          email: TODO_LE_EMAIL
          apiTokenSecretRef:
            name: cert-manager-secret
            key: CF_API_TOKEN
      selector:
        dnsZones:
        - TODO_ZONE
